### ISSUE TITLE
黃店-煲仔榮記

### ISSUE THREAD

**Issue by hkgaajau** [hkgaajau/yellow-blue-map#104]
元朗元朗東成里路1號地舖
https://www.openrice.com/zh/hongkong/r-煲仔榮記-元朗-港式-r779377

AndThen.hk
[https://www.andthen.hk/eat/13069_秋冬-誠意店-煲仔飯/](https://www.andthen.hk/eat/13069_%E7%A7%8B%E5%86%AC-%E8%AA%A0%E6%84%8F%E5%BA%97-%E7%85%B2%E4%BB%94%E9%A3%AF/)

**Comment by nothingmatter8964** [comment]
[Update] 旺角煲仔榮記已結業
https://s.openrice.com/QrRS0slaA00~u0-fSAw
