### ISSUE TITLE
觀塘區更新

### ISSUE THREAD

**Issue by nothingmatter8964** [hkgaajau/yellow-blue-map#108]
青木堂： 由駱駝漆搬去港貿15樓6室
鰹烏冬： 由駱駝漆2樓T 室搬去11樓O室
bluebluebluek:  觀塘店已結業
電氣生活館： 觀塘店已結業，轉營網店，office 在沙田
輕足適： 觀塘店已結業
Sensory zero:  店名錯誤mark 為觀塘廣場
NS workshop:  觀塘鋪已結業及轉型非party room
友情人/友情廚房/35座車仔麵：實體鋪已結業，友情廚房轉營網店

**Comment by hkgaajau** [comment]
根據Openrice, 鰹烏冬2樓T室仲喺度喎, 11樓好似係工場?

NS workshop我搵唔到佢轉型咗做乜野, 更新唔到...

其它會更新返, THANKS!
