### ISSUE TITLE
黃店 - JOMO Kitchen & Health Hub

### ISSUE THREAD

**Issue by cypatlo** [hkgaajau/yellow-blue-map#120]
---
title: 'JOMO Kitchen & Health Hub'
date: 2024-02-02
districts: 東區
colours: 黃店
categories: 食肆
lat: 22.2868511
lng: 114.2148819
source: hkchronicles
---
【商戶資料 / Shop Information】 <br>店名: JOMO Kitchen &amp; Health Hub<br>地址: 太古太裕路安盛臺地下501A號舖<br>電話: /<br>WhatsApp: /<br>營業時間: <br>星期一至日 08:00 - 20:00<br>公眾假期 08:00 - 20:00<br>網址: /<br>Facebook: <a href="https://www.facebook.com/JOMOCNC/">https://www.facebook.com/JOMOCNC/</a><br>Instagram: <a href="https://www.instagram.com/jomocoffeencakes/">https://www.instagram.com/jomocoffeencakes/</a><br>Openrice: <a href="https://www.openrice.com/zh/hongkong/r-jomo-kitchen-health-hub-%E5%A4%AA%E5%8F%A4-%E8%A5%BF%E5%BC%8F-%E7%84%A1%E8%82%89%E9%A4%90%E5%96%AE-r849567">https://www.openrice.com/zh/hongkong/r-jomo-kitchen-health-hub-%E5%A4%AA%E5%8F%A4-%E8%A5%BF%E5%BC%8F-%E7%84%A1%E8%82%89%E9%A4%90%E5%96%AE-r849567</a><br><br>相關連結: <a href="https://hkchronicles.com/d/view/ed14f11083ec6fc1">https://hkchronicles.com/d/view/ed14f11083ec6fc1</a>

**Comment by hkgaajau** [comment]
唔該晒啊，如果可以將個file整落個pull request俾我哋直接用就更好啦🥺

詳情可以睇睇呢度，個file要放落hugo/content/shops度
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests
