### ISSUE TITLE
 餃串party 

### ISSUE THREAD

**Issue by megid0105** [hkgaajau/yellow-blue-map#147]
長沙灣青山道368號喜韻商場地下2號舖

channel c, 基隆茶餐廳, 青木堂 到賀

https://youtu.be/L8ZH9iQLISs?si=DfnglQnVai2NPqpS

花藍睇片.

**Comment by hkgaajau** [comment]
喺《獨媒》落咗廣告:
https://www.google.com/maps/d/edit?mid=1VzyoB57loUEAq7D0Uk-ZUXKIiNd6YQY&usp=drive_link

下次更新會加落去
