### ISSUE TITLE
Luna Dessert

### ISSUE THREAD

**Issue by a0s1d2f30** [hkgaajau/yellow-blue-map#174]
係泰基隆嘅尖沙咀分店
https://www.facebook.com/share/p/aWnBtR6uwh2RsgV9/?mibextid=oFDknk

https://www.facebook.com/profile.php?id=61555702852919&mibextid=ZbWKwL
尖沙咀漆咸道南23-27號LUNA MARKET後鋪
（入口位於麼地道41至43號）

**Comment by hkgaajau** [comment]
唔好意思我入唔到你第一條link 介唔介意cap幅圖擺上嚟? 小心唔好cap到個人資料 🙏

**Comment by a0s1d2f30** [comment]
![Uploading Screenshot_20240518-182244_Facebook.jpg…]()

**Comment by hkgaajau** [comment]
Sorry 張相load唔到... 可以再upload多次嗎?

**Comment by a0s1d2f30** [comment]
![Screenshot_20240518-182244_Facebook](https://github.com/hkgaajau/yellow-blue-map/assets/125253007/4589c9a1-9ed4-40d1-8068-bcbeedf78092)
