### ISSUE TITLE
中西區黃區變動

### ISSUE THREAD

**Issue by enqprice** [hkgaajau/yellow-blue-map#202]
https://yellow-blue-map.pages.dev/shops/22.282-114.128-%E8%BC%95%E9%AC%86%E7%85%AE/
結業咗好耐

開左花斑
https://www.openrice.com/zh/hongkong/r-%E8%8A%B1%E6%96%91%E8%8C%B6%E7%A4%BE-%E8%A5%BF%E7%92%B0-%E5%8F%B0%E7%81%A3%E8%8F%9C-%E5%8F%B0%E5%BC%8F%E9%A3%B2%E5%93%81-r756586

soulfree 門店早沒了, 轉左做catering, openrice冇update
https://www.instagram.com/soulfreecatering?fbclid=IwZXh0bgNhZW0CMTAAAR3iTYAG9SY0ggVWjfRGJHdi51YSvxuPEW2tts2cjPw6tQjMACEMPW11ECo_aem_6YbMO8SOroUBd_hOra7pBQ

彩aya 對面開了間雞白湯branch
https://www.instagram.com/p/C8wBXUQSJZW/

蘇醫生冇做了
https://www.google.com/search?client=firefox-b-d&q=So+Kai+Ming

llb bistro 冇做了
https://www.facebook.com/llbbistrohk

見山冇了
https://www.google.com/search?client=firefox-b-d&q=%E8%A6%8B%E5%B1%B1

15squarestreet冇左好耐
https://www.openrice.com/en/hongkong/r-squarestreet-kaffe-sheung-wan-western-bakery-r638434

https://yellow-blue-map.pages.dev/shops/22.283-114.152-Carpe-Diem-%E6%97%85%E7%AA%A9/
5月尾冇做

https://www.openrice.com/zh/hongkong/r-life-%E8%A5%BF%E7%92%B0-%E8%A5%BF%E5%BC%8F-r756502
https://yellow-blue-map.pages.dev/shops/22.283-114.153-Life/
只剩西營盤

https://yellow-blue-map.pages.dev/shops/22.282-114.155-%E5%90%83%E4%BB%80%E9%BA%BC/
吃什麼沒了

https://yellow-blue-map.pages.dev/shops/22.282-114.153-%E7%82%BA%E9%A3%9F%E9%BE%8D/
為食龍沒了

**Comment by hkgaajau** [comment]
收到🫡🫡 下次會更新返

同埋有openrice link果d可以唔洗報 我地定期會scan下邊d執咗🙏
