### ISSUE TITLE
港島已結業資訊

### ISSUE THREAD

**Issue by MissYdirectory** [hkgaajau/yellow-blue-map#224]
中西區
**Cafeteria by Favilla** 
先改名學．食 Cafeteria @ HKU, 後結業
改名資訊: 
https://www.facebook.com/share/p/gVrJ6rR1sHKVDEUQ/
後結業
https://www.openrice.com/zh/hongkong/restaurants?whatwhere=%E5%AD%B8%EF%BC%8E%E9%A3%9F%20Cafeteria&tabIndex=0

**夏雪 Summer Ice**
https://www.openrice.com/zh/hongkong/r-%E5%A4%8F%E9%9B%AA-%E8%A5%BF%E7%92%B0-%E8%A5%BF%E5%BC%8F-%E7%94%9C%E5%93%81-%E7%B3%96%E6%B0%B4-r811842

**百里居**
https://www.openrice.com/zh/hongkong/r-%E7%99%BE%E9%87%8C%E5%B1%85-%E4%B8%AD%E7%92%B0-%E8%A5%BF%E5%BC%8F-%E6%B2%99%E5%BE%8B-r543677

### 南區
**鮨政**
https://www.openrice.com/zh/hongkong/r-%E9%AE%A8%E6%94%BF-%E9%A6%99%E6%B8%AF%E4%BB%94-%E6%97%A5%E6%9C%AC%E8%8F%9C-%E5%A3%BD%E5%8F%B8-%E5%88%BA%E8%BA%AB-r151029

### 灣仔
**Little Fresh Cafe & Bar**
https://www.instagram.com/littlefresh.cwb/p/C-S3-poSegi/

**Pheromone - Steak House**
https://www.facebook.com/share/p/tdKaev8tDK7CYXgh/ (留言有寫)

**Second Draft**  大坑店已搬遷至銅鑼灣
https://www.openrice.com/zh/hongkong/r-second-draft-%E5%A4%A7%E5%9D%91-%E5%A4%9A%E5%9C%8B%E8%8F%9C-r493585

**博多拉麵別天神**
https://www.openrice.com/zh/hongkong/r-%E5%8D%9A%E5%A4%9A%E6%8B%89%E9%BA%B5%E5%88%A5%E5%A4%A9%E7%A5%9E-%E9%8A%85%E9%91%BC%E7%81%A3-%E6%97%A5%E6%9C%AC%E8%8F%9C-%E6%8B%89%E9%BA%B5-r125552

**原汁原味** 已易手
https://www.openrice.com/zh/hongkong/r-%E5%8E%9F%E6%B1%81%E5%8E%9F%E5%91%B3-%E7%81%A3%E4%BB%94-%E6%B8%AF%E5%BC%8F-r40475

**空中棋園**
https://www.jollythinkers.com/

### 東區
凪豚骨拉麵
全線已結業, 東區本為工場

**泰金國**
https://www.openrice.com/zh/hongkong/r-%E6%B3%B0%E9%87%91%E5%9C%8B-%E5%8C%97%E8%A7%92-%E6%B3%B0%E5%9C%8B%E8%8F%9C-%E5%92%96%E5%96%B1-r742291

**陸拾六**
https://www.openrice.com/zh/hongkong/r-%E9%99%B8%E6%8B%BE%E5%85%AD-%E5%8C%97%E8%A7%92-%E8%A5%BF%E5%BC%8F-r560583

**Comment by hkgaajau** [comment]
原汁原味好似2015年易手 (睇openrice食評)? 即係唔關事?

其它會睇完再update, thanks!
