### ISSUE TITLE
Moojoo Lifestyle Cafe 大圍圍方

### ISSUE THREAD

**Issue by Tabascobra** [hkgaajau/yellow-blue-map#225]
坐低見到佢用印有pacific coffee嘅餐巾，應該同pacific coffee 有關係…

**Comment by hkgaajau** [comment]
多謝提供資料呀
Pacific Coffee都唔喺黃藍地圖入面，雖然好似係華潤集團... 以前有共業去label呢d紅底公司，而家都無咗囉 :(
要諗下點處理先
