### ISSUE TITLE
羅師傳家居維修

### ISSUE THREAD

**Issue by MRLAWCO** [hkgaajau/yellow-blue-map#228]
裝修工程、店鋪維修、寫字樓裝修、家居裝修、緊急維修、翻新工程、外牆滲水、水電、更換喉管、按裝冷氣、清洗冷氣、抽氣扇、電力工程、跳掣、更換燈具、檢測線路、上門度尺、大小工程，觀迎查詢。
聯絡電話：95237285羅師傅

**Comment by hkgaajau** [comment]
唔好意思呀 太少資料真係加唔到 起碼都要有黃藍資料來源
