### ISSUE TITLE
黃店 - Shop Point - 雜貨

### ISSUE THREAD

**Issue by shoppoint** [hkgaajau/yellow-blue-map#45]
【商戶資料 / Shop Information】
店名: Shop Point
類別: 零售/批發
詳細分類: 糧油雜貨, 酒, 咖啡, 茶, 健康食品, 零食, 蔘茸海味, 日用品, 女性用品, 護膚品, 化妝品, 卡通精品, 營養補充品, 清潔用品, 寵物用品, 餐具, 家品, 調味料, 母嬰用品, 玩具

地址: 旺角廣華街42-56號廣發商業中心11/F 1101室
Whatsapp: 26926068

網址: https://shoppoint.hk
Facebook: https://www.facebook.com/shoppoint.hk
Instagram: https://www.instagram.com/shoppoint.hk

產品/服務:
零食, 調味料, 醬料, 糖, 杯麵, 米, 飲品, 紅酒, 白酒, 清酒, 果酒, 葡萄酒, miffy, 鬆弛熊, 角落生物, 個人護理用品, 廚具, 日本藥粧, 驅蟲用品, 酒壺, 面膜

**Comment by hkgaajau** [comment]
和你撐良心店（非餐廳食肆）
https://www.facebook.com/HKYellowshopfb/posts/pfbid0hhGQi51S5Y44eHNmUkKgovEFkqfugqWCEeskCgnArSLczh9L1TZekD7bQEvUwJmel
