### ISSUE TITLE
黃店-復修辦館 Repair Cafe HK（資料更新）

### ISSUE THREAD

**Issue by ReporterX** [hkgaajau/yellow-blue-map#59]
https://yellow-blue-map.pages.dev/shops/22.366-114.141-Repair-Cafe-Hong-Kong-%E5%BE%A9%E4%BF%AE%E5%86%B0%E5%AE%A4/

部分資料有誤或遺漏，需要更新
名稱有誤，官方名稱為「[復修辦館 Repair Cafe HK](https://www.repaircafehk.org/)」
更新資料來源可參看它FB專頁

====

部分資料有誤或遺漏，需要更新
**粗體**為要更新部分

店名: ~~Repair Cafe Hong Kong 復修冰室~~ **復修辦館 Repair Cafe HK**
類別: 家居服務
詳細分類: 家居電器, 水電冷氣, 電子維修
地址: ~~葵涌石梨街18號1樓~~ **九龍新蒲崗大有街35號義發工業大廈9/F A3室**
電話: **9852 6144**
營業時間:
歡迎查詢
網址/電郵: ~~repaircafe_hk@communityleap.com~~ **repaircafehongkong@gmail.com**
Facebook: https://www.facebook.com/repaircafehk/
Instagram: **https://www.instagram.com/repaircafe_hk/**

**Comment by digimon04** [comment]
其實名(復修冰室)同地址都無錯, 錯的是社交專頁網址
復修冰室有明確支持社運, 所在地址(石梨)係前職工盟培訓中心
復修冰室今年改名做**復修號**
https://www.facebook.com/VesselREPAIR/

復修辦館係另一個團體, 位於新蒲崗, 雖然有黃店參與, 米紙都有拍片介紹, 但係復修辦館暫時無資料表明立場

請更新資料, thanks
