### ISSUE TITLE
黃店-復修號（資料更新）

### ISSUE THREAD

**Issue by ReporterX** [hkgaajau/yellow-blue-map#61]
此店前身正是「Repair Cafe Hong Kong 復修冰室」

![image](https://github.com/hkgaajau/yellow-blue-map/assets/8235338/bd93d036-d6b2-4972-927b-a5a5e7e53999)（[截圖來源](https://www.facebook.com/VesselREPAIR/about_profile_transparency)）

可是我初初誤會是名稱出錯，[以為它應該叫復修辦館](https://github.com/hkgaajau/yellow-blue-map/issues/59)

當時復修冰室的名稱是正確，當時地址也是正確，出錯的是Facebook連結，指向了另一間店舖復修辦館（[參考來源](https://github.com/hkgaajau/yellow-blue-map/issues/59#issuecomment-1791589882)）

故需要再作更正

----

https://yellow-blue-map.pages.dev/shops/22.336-114.197-%E5%BE%A9%E4%BF%AE%E8%BE%A6%E9%A4%A8-Repair-Cafe-HK/

**粗體**為需要更新部分

【商戶資料 / Shop Information】
店名: **復修號**
類別: 家居服務
詳細分類: 家居電器, 水電冷氣, 電子維修
地址: **葵涌和宜合道131號恆利中心9樓**
電話: **[9180 7458](https://wa.me/85291807458)**
營業時間:
網址/電郵: **https://linktr.ee/VesselRepair**
Facebook: **https://www.facebook.com/VesselREPAIR/**
Instagram: **https://www.instagram.com/vessel_repair/**

**Comment by hkgaajau** [comment]
多謝你提供嘅資料呀，我下次都會check得小心啲先再更新！
