### ISSUE TITLE
已結業的黃店

### ISSUE THREAD

**Issue by cypatlo** [hkgaajau/yellow-blue-map#62]
東區: 

[Favilla Cafe](https://yellow-blue-map.pages.dev/shops/22.288-114.211-Favilla-Cafe/)

[齊柏林熱狗店 Zeppelin Hot Dog Shop](https://yellow-blue-map.pages.dev/shops/22.288-114.212-%E9%BD%8A%E6%9F%8F%E6%9E%97%E7%86%B1%E7%8B%97%E5%BA%97-Zeppelin-Hot-Dog-Shop/)

[吃什麼](https://yellow-blue-map.pages.dev/shops/22.284-114.213-%E5%90%83%E4%BB%80%E9%BA%BC/)

灣仔區：

[文華饕記](https://yellow-blue-map.pages.dev/shops/22.278-114.177-%E6%96%87%E8%8F%AF%E9%A5%95%E8%A8%98/)

**Comment by hkgaajau** [comment]
多謝你嘅報料呀！同埋如果店舖資料入面有openrice link的話(e.g. [Favilla Cafe](https://yellow-blue-map.pages.dev/shops/22.288-114.211-Favilla-Cafe/), [文華饕記](https://yellow-blue-map.pages.dev/shops/22.278-114.177-%E6%96%87%E8%8F%AF%E9%A5%95%E8%A8%98/))，我地會定期掃下結業未㗎，唔需要再花時間額外報料 =]
